---
# Reference:
# https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-16.04/cuda/8.0/runtime/cudnn5/Dockerfile

- name: Check whether cuDNN exists or not
  stat: path=/usr/local/cuda/include/cudnn.h
  register: cudnn_header

- name: Download cuDNN
  get_url:
    url: http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/cudnn-8.0-linux-x64-v6.0.tgz
    dest: /tmp/cudnn-8.0-linux-x64-v6.0-tgz
    checksum: sha256:36e7cd54d9f4cd448c302a40d2ed530a643e3ae32797a67739448ebe7c9f0620
  when: not cudnn_header.stat.exists

- unarchive: creates=/usr/local/cuda/include/cudnn.h src=/tmp/cudnn-8.0-linux-x64-v6.0-tgz dest=/usr/local owner=root group=root mode=0644
- file: path=/tmp/cudnn-8.0-linux-x64-v6.0-tgz state=absent
