---
- apt: name={{item}} state=latest
  with_items:
  - python3
  - python3-dev
  - libssl-dev
  - libffi-dev
  - python3-pip

- pip: name=pip state=latest executable=pip3
- pip: name={{item}} state=latest executable=pip3
  with_items:
  - setuptools
  - wheel

